# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_poke_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poke_history', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='poke',
            name='getting_poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getting_poked', to='test_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='is_poking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_poking', to='test_app.User'),
        ),
    ]
